// Code generated by generator -n 4 -f mapping/mapping.template -o mapping/mapping.pb.go; DO NOT EDIT.
package main

import (
	"gxn.tw/performance/switch-or-map/pkg/plugs"
)

var (
	Factory  plugs.Factory
	store = map[string]string{
		"aal": "aalii",
		"aam": "Aani",
		"aardvark": "aardwolf",
		"Aaron": "Aaronic",
		
	}
)

func init() {
	Factory = func() plugs.Getter { return &wrapper{} }
}

type wrapper struct {}

func (w *wrapper) Get(key string) (string, bool) {
	v, ok := store[key]
	return v, ok
}
