// Code generated by generator -n 4 -f switching/switching.template -o switching/switching.pb.go; DO NOT EDIT.
package main

import (
	"gxn.tw/performance/switch-or-map/pkg/plugs"
)

var (
	Factory plugs.Factory
)

func init() {
	Factory = func() plugs.Getter { return &wrapper{} }
}

type wrapper struct {}

func (w *wrapper) Get(key string) (string, bool) {
	switch key {

	case "aal":
		return "aalii", true

	case "aam":
		return "Aani", true

	case "aardvark":
		return "aardwolf", true

	case "Aaron":
		return "Aaronic", true

	}
	return "", false
}
